// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
    
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDQnIoumsfP0ImGTl8uU-Oo1EJXu9teDc',
    appId: '1:400315761727:web:0f42aab33f099bc720248a',
    messagingSenderId: '400315761727',
    projectId: 'makanmate-44f9e',
    authDomain: 'makanmate-44f9e.firebaseapp.com',
    storageBucket: 'makanmate-44f9e.firebasestorage.app',
    measurementId: 'G-8T5FW31H9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5a0YQEtyVKKVxWqeHqIzgMdSItEWZbEI',
    appId: '1:400315761727:android:54f830ce49e235f520248a',
    messagingSenderId: '400315761727',
    projectId: 'makanmate-44f9e',
    storageBucket: 'makanmate-44f9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEzmlD6WRkbXyjnmL1fSCwx-ZcMl_veok',
    appId: '1:400315761727:ios:5b41f05effc160f220248a',
    messagingSenderId: '400315761727',
    projectId: 'makanmate-44f9e',
    storageBucket: 'makanmate-44f9e.firebasestorage.app',
    iosBundleId: 'com.example.makanMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEzmlD6WRkbXyjnmL1fSCwx-ZcMl_veok',
    appId: '1:400315761727:ios:5b41f05effc160f220248a',
    messagingSenderId: '400315761727',
    projectId: 'makanmate-44f9e',
    storageBucket: 'makanmate-44f9e.firebasestorage.app',
    iosBundleId: 'com.example.makanMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDQnIoumsfP0ImGTl8uU-Oo1EJXu9teDc',
    appId: '1:400315761727:web:cabffdb8c43534a420248a',
    messagingSenderId: '400315761727',
    projectId: 'makanmate-44f9e',
    authDomain: 'makanmate-44f9e.firebaseapp.com',
    storageBucket: 'makanmate-44f9e.firebasestorage.app',
    measurementId: 'G-VPQ7BT4KCW',
  );
  

}